spring:
  #  datasource:
  #    url: jdbc:h2:mem:testdb
  #    driver-class-name: org.h2.Driver
  #    username: sa
  #    password:
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
#    hibernate:
#      ddl-auto: create

server:
  port: 18080
  shutdown: graceful

example:
  order:
    base-url: http://localhost:8080

cloud:
  aws:
    access-key: aaaa
    secret-key: bbbb